apiVersion: 1

datasources:
  - name: EnviroPlus SQLite
    type: frser-sqlite-datasource
    uid: cfhpdda09qq68e
    access: proxy
    jsonData:
      path: /data/enviroplus/enviro.db
    version: 1
    editable: true

  - name: Stocks SQLite
    type: frser-sqlite-datasource
    uid: stocks-sqlite-ds
    access: proxy
    jsonData:
      path: /data/stocks/stocks.db
    version: 1
    editable: true

  - name: PiHoleWatch SQLite
    type: frser-sqlite-datasource
    uid: pihole-watch-sqlite-ds
    access: proxy
    jsonData:
      path: /data/pihole-watch/findings.db
    version: 1
    editable: true
